# Generated by Django 5.2.17 on 2026-08-12 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
        ('venues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('kind', models.CharField(choices=[('observations', 'Cover and vibes'), ('deal_evidence', 'Deal evidence')], max_length=24)),
                ('observed_at_client', models.DateTimeField()),
                ('received_at_server', models.DateTimeField(auto_now_add=True)),
                ('time_quality', models.CharField(choices=[('unassessed', 'Unassessed'), ('plausible', 'Plausible'), ('future_skew', 'Future skew'), ('stale_interaction', 'Stale interaction')], default='unassessed', max_length=24)),
                ('vantage_point', models.CharField(choices=[('outside', 'Outside'), ('inside', 'Inside'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('client_platform', models.CharField(blank=True, max_length=24)),
                ('client_version', models.CharField(blank=True, max_length=40)),
                ('entry_point', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='venues.venue')),
            ],
            options={
                'ordering': ('-observed_at_client', '-received_at_server'),
            },
        ),
        migrations.CreateModel(
            name='SubmissionPrivateContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_accuracy_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('location_permission', models.CharField(blank=True, max_length=24)),
                ('network_verifier', models.CharField(blank=True, max_length=64)),
                ('erased_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission_contexts', to=settings.AUTH_USER_MODEL)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission_contexts', to='identity.installationactor')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='private_context', to='submissions.submission')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('latitude__isnull', True), ('longitude__isnull', True)), models.Q(('latitude__isnull', False), ('longitude__isnull', False)), _connector='OR'), name='private_location_complete_pair')],
            },
        ),
    ]
