# Generated by Django 5.2.17 on 2026-08-12 12:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='source_kind',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='submission',
            name='source_record_key',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='received_at_server',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
