# Generated by Django 5.2.17 on 2026-08-12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0002_submission_source_kind_submission_source_record_key_and_more")
    ]

    operations = [
        migrations.CreateModel(
            name="SubmissionRateBucket",
            fields=[
                ("key", models.CharField(max_length=180, primary_key=True, serialize=False)),
                ("count", models.PositiveIntegerField(default=0)),
                ("expires_at", models.DateTimeField(db_index=True)),
            ],
        )
    ]
