# Generated by Django 5.2.17 on 2026-08-31 00:47

import django.db.models.deletion
import django.utils.timezone
import product.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllauthRateLimitCache',
            fields=[
                ('cache_key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('expires', models.DateTimeField(db_index=True)),
            ],
            options={
                'db_table': 'allauth_rate_limits',
            },
        ),
        migrations.CreateModel(
            name='HandbookPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('summary', models.TextField(blank=True)),
                ('body_markdown', models.TextField()),
                ('published', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('published_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('sort_order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='ProviderDeletionRequest',
            fields=[
                ('provider_customer_id', models.CharField(max_length=160, primary_key=True, serialize=False)),
                ('queued', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RateBucket',
            fields=[
                ('key', models.CharField(max_length=180, primary_key=True, serialize=False)),
                ('count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('observations', 'Cover and vibes'), ('deal_evidence', 'Deal evidence')], max_length=24)),
                ('observed_at_client', models.DateTimeField()),
                ('received_at_server', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_quality', models.CharField(default='plausible', max_length=24)),
                ('vantage_point', models.CharField(default='unknown', max_length=16)),
                ('client_platform', models.CharField(blank=True, max_length=24)),
                ('entry_point', models.CharField(blank=True, max_length=40)),
                ('source_record_key', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('independence_group', models.UUIDField(null=True)),
                ('cover_price_cents', models.PositiveIntegerField(null=True)),
                ('cover_interaction', models.CharField(blank=True, max_length=24)),
                ('cover_echo', models.JSONField(default=dict)),
                ('vibes', models.JSONField(default=list)),
                ('trust', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ('-observed_at_client', '-received_at_server'),
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(blank=True, max_length=240)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('opened_year', models.PositiveSmallIntegerField(null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=80)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', product.models.AccountManager()),
            ],
        ),
        migrations.CreateModel(
            name='AccountEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entitlement', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DealFamily',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canonical_name', models.CharField(max_length=160)),
                ('category', models.CharField(max_length=40)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('category', 'canonical_name'), name='unique_deal_family')],
            },
        ),
        migrations.CreateModel(
            name='InstallationActor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verifier', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RevenueCatEvent',
            fields=[
                ('provider_event_id', models.CharField(max_length=160, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SessionTokenVerifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verifier', models.CharField(max_length=64, unique=True)),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_token_verifiers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DealEvidenceEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=24)),
                ('target_id', models.UUIDField(null=True)),
                ('submitted_shape', models.JSONField(null=True)),
                ('service_date_local', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deal_event', to='product.submission')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionPrivateContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('location_accuracy_m', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('location_permission', models.CharField(blank=True, max_length=24)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission_contexts', to=settings.AUTH_USER_MODEL)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission_contexts', to='product.installationactor')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='private_context', to='product.submission')),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='product.venue'),
        ),
        migrations.CreateModel(
            name='HistoricalDealFact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_record_key', models.CharField(max_length=500, unique=True)),
                ('source', models.CharField(max_length=500)),
                ('display_name', models.CharField(max_length=180)),
                ('price_kind', models.CharField(max_length=24)),
                ('price_cents', models.PositiveIntegerField(null=True)),
                ('discount_percent', models.DecimalField(decimal_places=3, max_digits=8, null=True)),
                ('unit', models.CharField(blank=True, max_length=120)),
                ('service_date_local', models.DateField()),
                ('timing_description', models.CharField(blank=True, max_length=160)),
                ('while_supplies_last', models.BooleanField(default=False)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facts', to='product.dealfamily')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_deals', to='product.venue')),
            ],
        ),
        migrations.CreateModel(
            name='AdvertisedAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_cents', models.PositiveIntegerField()),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(null=True)),
                ('qualification', models.CharField(blank=True, max_length=240)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('provenance', models.CharField(max_length=500)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertised_admissions', to='product.venue')),
            ],
        ),
    ]
