steps:
  - name: gcr.io/cloud-builders/docker@sha256:bbb3d633c5c2813b2ce5245852979e1d637768f4acfc504d8ece288f91e9b60f
    args:
      - build
      - --build-arg
      - CODE_REVISION=${_CODE_REVISION}
      - --tag
      - ${_IMAGE}
      - --file
      - ops/container/Dockerfile
      - .
images:
  - ${_IMAGE}
options:
  machineType: E2_STANDARD_2
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _IMAGE: us-east5-docker.pkg.dev/illinicover/illinicover/backend:IMMUTABLE_REVISION_REQUIRED
  _CODE_REVISION: IMMUTABLE_REVISION_REQUIRED
