# Generated by Django 5.2.17 on 2026-08-12 12:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=160, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DealEvidenceEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('ADD_MISSING', 'Add missing'), ('CONFIRM_PRESENT', 'Confirm present'), ('DENY_PRESENT', 'Deny present'), ('CORRECT', 'Correct')], max_length=24)),
                ('target_prediction_id', models.UUIDField(blank=True, null=True)),
                ('submitted_deal_shape', models.JSONField(blank=True, null=True)),
                ('service_date_local', models.DateField()),
                ('target_local_datetime', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DealFamily',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canonical_name', models.CharField(max_length=160, unique=True)),
                ('category', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DealDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=180)),
                ('category', models.CharField(max_length=40)),
                ('price_kind', models.CharField(max_length=24)),
                ('price_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('unit', models.CharField(blank=True, max_length=80)),
                ('serving_format', models.CharField(blank=True, max_length=120)),
                ('timing_description', models.CharField(blank=True, max_length=160)),
                ('timing_known', models.BooleanField(default=False)),
                ('while_supplies_last', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deal_definitions', to='venues.venue')),
            ],
        ),
    ]
