# Generated by Django 5.2.17 on 2026-08-12 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deals', '0001_initial'),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealevidenceevent',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='deal_evidence_event', to='submissions.submission'),
        ),
        migrations.AddField(
            model_name='dealevidenceevent',
            name='supersedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='deals.dealevidenceevent'),
        ),
        migrations.AddField(
            model_name='dealevidenceevent',
            name='target_deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidence_events', to='deals.dealdefinition'),
        ),
        migrations.AddField(
            model_name='dealdefinition',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='definitions', to='deals.dealfamily'),
        ),
        migrations.AddField(
            model_name='dealalias',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='deals.dealfamily'),
        ),
    ]
