# Generated by Django 5.2.17 on 2026-08-12 12:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_initial'),
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealfamily',
            name='source_identifier',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='HistoricalDealFact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_record_key', models.CharField(max_length=500, unique=True)),
                ('source_dataset', models.CharField(max_length=120)),
                ('display_name', models.CharField(max_length=180)),
                ('category', models.CharField(max_length=40)),
                ('price_kind', models.CharField(max_length=24)),
                ('price_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('relative_percent', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('unit', models.CharField(blank=True, max_length=120)),
                ('service_date_local', models.DateField()),
                ('timing_kind', models.CharField(max_length=40)),
                ('timing_start_local', models.TimeField(blank=True, null=True)),
                ('timing_end_local', models.TimeField(blank=True, null=True)),
                ('timing_time_local', models.TimeField(blank=True, null=True)),
                ('while_supplies_last', models.BooleanField(default=False)),
                ('source_post_key', models.CharField(max_length=300)),
                ('source_payload_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historical_facts', to='deals.dealfamily')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historical_deal_facts', to='venues.venue')),
            ],
        ),
    ]
