# Generated by Django 5.2.17 on 2026-08-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0004_dealdefinition_prediction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealfamily',
            name='canonical_name',
            field=models.CharField(max_length=160),
        ),
        migrations.AddConstraint(
            model_name='dealfamily',
            constraint=models.UniqueConstraint(fields=('category', 'canonical_name'), name='unique_deal_family_name_per_category'),
        ),
    ]
