# Generated by Django 5.2.17 on 2026-08-12 12:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0005_alter_dealfamily_canonical_name_and_more'),
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealPredictionRelease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('predictor_version', models.CharField(max_length=80)),
                ('code_revision', models.CharField(max_length=80)),
                ('training_data_revision', models.CharField(max_length=160)),
                ('parameters', models.JSONField(default=dict)),
                ('evaluation_metrics', models.JSONField(default=dict)),
                ('is_authoritative', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('promoted_at', models.DateTimeField(blank=True, null=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('predictor_version', 'training_data_revision'), name='unique_deal_prediction_release'), models.UniqueConstraint(condition=models.Q(('is_authoritative', True)), fields=('is_authoritative',), name='one_authoritative_deal_predictor')],
            },
        ),
        migrations.CreateModel(
            name='DealPrediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_date_local', models.DateField()),
                ('support_nights', models.PositiveIntegerField()),
                ('comparable_nights', models.PositiveIntegerField()),
                ('latest_evidence_date', models.DateField()),
                ('status', models.CharField(default='likely', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='predictions', to='deals.dealdefinition')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deal_predictions', to='venues.venue')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='predictions', to='deals.dealpredictionrelease')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('release', 'venue', 'deal_definition', 'service_date_local'), name='unique_deal_prediction')],
            },
        ),
    ]
