# Generated by Django 5.2.17 on 2026-08-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("deals", "0006_dealpredictionrelease_dealprediction")]

    operations = [
        migrations.AddField(
            model_name="dealevidenceevent",
            name="target_evidence",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="targeted_by",
                to="deals.dealevidenceevent",
            ),
        )
    ]
