# Generated by Django 5.2.17 on 2026-08-12 12:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_time', models.DateTimeField()),
                ('knowledge_cutoff', models.DateTimeField()),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('result_price_kind', models.CharField(choices=[('single', 'Single'), ('range', 'Range'), ('unavailable', 'Unavailable')], max_length=16)),
                ('result_price_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('result_low_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('result_high_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('source', models.CharField(choices=[('live', 'Live'), ('historical', 'Historical'), ('mixed', 'Mixed'), ('unconfirmed', 'Unconfirmed'), ('unavailable', 'Unavailable')], max_length=24)),
                ('status', models.CharField(max_length=24)),
                ('model_release_id', models.UUIDField(blank=True, null=True)),
                ('evidence_revision', models.CharField(max_length=80)),
                ('context_revision', models.CharField(blank=True, max_length=80)),
                ('resolver_version', models.CharField(max_length=80)),
                ('same_night_adjustment_summary', models.JSONField(default=dict)),
                ('campus_adjustment_summary', models.JSONField(default=dict)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cover_decisions', to='venues.venue')),
            ],
            options={
                'ordering': ('-computed_at',),
            },
        ),
        migrations.CreateModel(
            name='CoverObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_price_cents', models.PositiveIntegerField()),
                ('interaction_kind', models.CharField(choices=[('confirm', 'Confirm'), ('correct', 'Correct'), ('direct', 'Direct'), ('quick_confirm', 'Quick confirm'), ('manual', 'Manual')], max_length=24)),
                ('displayed_source', models.CharField(blank=True, max_length=24)),
                ('displayed_price_kind', models.CharField(blank=True, max_length=16)),
                ('displayed_price_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('displayed_price_low_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('displayed_price_high_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('price_prefilled', models.BooleanField(default=False)),
                ('price_touched', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('displayed_decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirming_observations', to='covers.coverdecision')),
            ],
        ),
    ]
