# Generated by Django 5.2.17 on 2026-08-12 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('covers', '0001_initial'),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverobservation',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cover_observation', to='submissions.submission'),
        ),
        migrations.AddConstraint(
            model_name='coverdecision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('result_price_cents__isnull', False), ('result_price_kind', 'single')), models.Q(('result_high_cents__isnull', False), ('result_low_cents__isnull', False), ('result_price_kind', 'range')), ('result_price_kind', 'unavailable'), _connector='OR'), name='cover_decision_price_shape'),
        ),
    ]
