# Generated by Django 5.2.17 on 2026-08-12 12:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covers', '0003_coverobservation_source_dataset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coverdecision',
            name='model_release_id',
        ),
        migrations.CreateModel(
            name='CoverModelRelease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_kind', models.CharField(max_length=80)),
                ('model_version', models.CharField(max_length=80)),
                ('code_revision', models.CharField(max_length=80)),
                ('training_data_revision', models.CharField(max_length=160)),
                ('context_feature_revision', models.CharField(blank=True, max_length=160)),
                ('parameters_or_artifact', models.JSONField(default=dict)),
                ('evaluation_metrics', models.JSONField(default=dict)),
                ('is_authoritative', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('promoted_at', models.DateTimeField(blank=True, null=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('model_kind', 'model_version'), name='unique_cover_model_version'), models.UniqueConstraint(condition=models.Q(('is_authoritative', True)), fields=('is_authoritative',), name='one_authoritative_cover_model')],
            },
        ),
        migrations.AddField(
            model_name='coverdecision',
            name='model_release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='covers.covermodelrelease'),
        ),
    ]
