# Generated by Django 5.2.17 on 2026-08-12 12:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covers', '0004_remove_coverdecision_model_release_id_and_more'),
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverTrainingRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_revision', models.CharField(max_length=160, unique=True)),
                ('knowledge_cutoff', models.DateTimeField()),
                ('service_nights', models.PositiveIntegerField()),
                ('observations_seen', models.PositiveIntegerField()),
                ('observations_admitted', models.PositiveIntegerField()),
                ('provenance', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShadowCoverPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_time', models.DateTimeField()),
                ('knowledge_cutoff', models.DateTimeField()),
                ('result_price_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('result_low_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('result_high_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shadow_predictions', to='covers.covermodelrelease')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shadow_predictions', to='venues.venue')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('venue', 'model_release', 'target_time', 'knowledge_cutoff'), name='unique_shadow_cover_prediction')],
            },
        ),
    ]
