# Generated by Django 5.2.17 on 2026-08-12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("covers", "0005_covertrainingrevision_shadowcoverprediction")]

    operations = [
        migrations.AddField(
            model_name="coverobservation",
            name="deidentified_independence_key",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="coverobservation",
            name="admission_snapshot",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="coverobservation",
            name="independence_group_key",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
