# Generated by Django 5.2.17 on 2026-08-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covers', '0006_coverobservation_deidentified_independence_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverdecision',
            name='source',
            field=models.CharField(choices=[('live', 'Live'), ('advertised', 'Advertised'), ('historical', 'Historical'), ('mixed', 'Mixed'), ('unconfirmed', 'Unconfirmed'), ('unavailable', 'Unavailable')], max_length=24),
        ),
    ]
