# Generated by Django 5.2.17 on 2026-08-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covers', '0007_alter_coverdecision_source'),
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverdecision',
            name='served_state_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='coverdecision',
            constraint=models.UniqueConstraint(fields=('venue', 'target_time', 'knowledge_cutoff', 'evidence_revision'), name='unique_exact_cover_decision_receipt'),
        ),
    ]
