# Generated by Django 5.2.17 on 2026-08-12

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("covers", "0008_coverdecision_served_state_key_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoverModelEvaluationReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("protocol_version", models.CharField(max_length=80)),
                ("evaluator_code_revision", models.CharField(max_length=80)),
                ("evaluation_start", models.DateTimeField()),
                ("evaluation_cutoff", models.DateTimeField()),
                ("challenger_artifact_sha256", models.CharField(max_length=64)),
                ("incumbent_artifact_sha256", models.CharField(max_length=64)),
                ("row_selection_sha256", models.CharField(max_length=64)),
                ("metrics", models.JSONField(default=dict)),
                ("gates", models.JSONField(default=dict)),
                ("not_evaluable_dimensions", models.JSONField(default=dict)),
                ("challenger_won", models.BooleanField(default=False)),
                ("promotion_eligible", models.BooleanField(default=False)),
                ("receipt_sha256", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "challenger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="challenger_evaluation_receipts",
                        to="covers.covermodelrelease",
                    ),
                ),
                (
                    "challenger_training_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="challenger_evaluation_receipts",
                        to="covers.covertrainingrevision",
                    ),
                ),
                (
                    "evaluation_data_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evaluation_receipts",
                        to="covers.covertrainingrevision",
                    ),
                ),
                (
                    "incumbent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incumbent_evaluation_receipts",
                        to="covers.covermodelrelease",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "protocol_version",
                            "challenger",
                            "incumbent",
                            "evaluation_data_revision",
                        ),
                        name="unique_cover_model_evaluation",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("evaluation_cutoff__gt", models.F("evaluation_start"))
                        ),
                        name="cover_model_evaluation_positive_window",
                    ),
                ]
            },
        ),
    ]
