# Generated by Django 5.2.17 on 2026-08-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_providerdeletionrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerdeletionrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued at provider'), ('succeeded', 'Succeeded')], default='pending', max_length=16),
        ),
    ]
