# Generated by Django 5.2.17 on 2026-08-12 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_event_environments(apps, schema_editor):
    RevenueCatEvent = apps.get_model('billing', 'RevenueCatEvent')
    for event in RevenueCatEvent.objects.all().iterator():
        payload = event.payload if isinstance(event.payload, dict) else {}
        event_payload = payload.get('event', {})
        environment = (
            event_payload.get('environment') if isinstance(event_payload, dict) else None
        )
        normalized = str(environment or '').strip().lower()
        if normalized in {'sandbox', 'production'}:
            event.environment = normalized
            event.save(update_fields=['environment'])


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_providerdeletionrequest_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accountentitlement',
            name='environment',
            field=models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production'), ('provider_aggregate', 'Provider aggregate')], default='provider_aggregate', max_length=24),
        ),
        migrations.AddField(
            model_name='revenuecatevent',
            name='environment',
            field=models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production'), ('unknown', 'Unknown or not supplied')], default='unknown', max_length=16),
        ),
        migrations.RunPython(
            backfill_event_environments,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='accountentitlement',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='accountentitlement',
            constraint=models.UniqueConstraint(fields=('account', 'entitlement_identifier', 'environment'), name='unique_account_entitlement_environment'),
        ),
    ]
