# Generated by Django 5.2.17 on 2026-08-12 23:01

import django.utils.timezone
from django.db import migrations, models
from django.db.models import F


def backfill_local_authority_clock(apps, schema_editor):
    AccountEntitlement = apps.get_model("billing", "AccountEntitlement")
    AccountEntitlement.objects.update(authority_observed_at=F("updated_at"))


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_accountentitlement_environment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountentitlement',
            name='authority_observed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(
            backfill_local_authority_clock,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='accountentitlement',
            name='authority_observed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
