# Generated by Django 5.2.17 on 2026-08-12 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VibeObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(choices=[('line_length', 'Line length'), ('line_speed', 'Line speed'), ('crowd_level', 'Crowd level')], max_length=24)),
                ('value', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vibe_observations', to='submissions.submission')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('submission', 'dimension'), name='one_vibe_dimension_per_submission'), models.CheckConstraint(condition=models.Q(models.Q(('dimension', 'line_length'), ('value__in', ('short', 'medium', 'long'))), models.Q(('dimension', 'line_speed'), ('value__in', ('slow', 'normal', 'fast'))), models.Q(('dimension', 'crowd_level'), ('value__in', ('quiet', 'busy', 'packed'))), _connector='OR'), name='vibe_value_matches_dimension')],
            },
        ),
    ]
