# Generated by Django 5.2.17 on 2026-08-12 12:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=120)),
                ('actor_kind', models.CharField(max_length=40)),
                ('actor_reference', models.CharField(blank=True, max_length=160)),
                ('target_reference', models.CharField(blank=True, max_length=160)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('code_revision', models.CharField(blank=True, max_length=80)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='running', max_length=24)),
                ('error', models.TextField(blank=True)),
                ('result_summary', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='DatasetRelease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('content_hash', models.CharField(max_length=64)),
                ('schema_version', models.CharField(max_length=40)),
                ('importer_version', models.CharField(max_length=80)),
                ('source_manifest', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'content_hash'), name='unique_dataset_content_release')],
            },
        ),
        migrations.CreateModel(
            name='DatasetImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_revision', models.CharField(max_length=80)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('rows_seen', models.PositiveIntegerField(default=0)),
                ('rows_accepted', models.PositiveIntegerField(default=0)),
                ('rows_rejected', models.PositiveIntegerField(default=0)),
                ('result', models.CharField(default='running', max_length=24)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_runs', to='operations.datasetrelease')),
            ],
        ),
    ]
