# Generated by Django 5.2.17 on 2026-08-12 12:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_identifier', models.CharField(max_length=120, unique=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SourceFetch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_identifier', models.CharField(max_length=120)),
                ('fetched_at', models.DateTimeField()),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('external_key', models.CharField(blank=True, max_length=200)),
                ('payload_hash', models.CharField(max_length=64)),
                ('parser_version', models.CharField(max_length=80)),
                ('status', models.CharField(max_length=24)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source_identifier', 'external_key', 'payload_hash'), name='unique_source_payload')],
            },
        ),
    ]
