# Generated by Django 5.2.17 on 2026-08-12 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0001_initial'),
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisedAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_cents', models.PositiveIntegerField()),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('qualification', models.CharField(blank=True, max_length=240)),
                ('is_unconditional', models.BooleanField(default=False)),
                ('source_fetch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advertised_admissions', to='context.sourcefetch')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advertised_admissions', to='venues.venue')),
            ],
        ),
        migrations.CreateModel(
            name='SportsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(max_length=80)),
                ('opponent', models.CharField(blank=True, max_length=160)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_home', models.BooleanField(default=False)),
                ('external_key', models.CharField(max_length=200, unique=True)),
                ('source_fetch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sports_events', to='context.sourcefetch')),
            ],
        ),
        migrations.CreateModel(
            name='TraditionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('service_date_local', models.DateField()),
                ('provenance', models.CharField(max_length=240)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'service_date_local'), name='unique_tradition_event')],
            },
        ),
        migrations.CreateModel(
            name='VenueEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('source_fetch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='venue_events', to='context.sourcefetch')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='context_events', to='venues.venue')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=160)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('source_fetch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_periods', to='context.sourcefetch')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('kind', 'name', 'starts_at', 'ends_at'), name='unique_academic_period')],
            },
        ),
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField()),
                ('valid_at', models.DateTimeField()),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('precipitation_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('wind_speed_mps', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('source_fetch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weather_records', to='context.sourcefetch')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('valid_at', 'source_fetch'), name='unique_weather_record_per_fetch')],
            },
        ),
    ]
