# Generated by Django 5.2.17 on 2026-08-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllauthRateLimitCache',
            fields=[
                ('cache_key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('expires', models.DateTimeField(db_index=True)),
            ],
            options={
                'verbose_name': 'allauth rate-limit cache entry',
                'verbose_name_plural': 'allauth rate-limit cache entries',
                'db_table': 'allauth_rate_limits',
            },
        ),
    ]
