# Generated by Django 5.2.17 on 2026-08-12 15:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0002_allauthratelimitcache"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountDeletionReceipt",
            fields=[
                (
                    "request_id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("completed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name="IdentityRateBucket",
            fields=[
                (
                    "key",
                    models.CharField(max_length=180, primary_key=True, serialize=False),
                ),
                ("count", models.PositiveIntegerField(default=0)),
                ("expires_at", models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.AddField(
            model_name="actoraccountlink",
            name="request_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name="InstallationOperationReceipt",
            fields=[
                (
                    "request_id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[("create", "Create"), ("rotate", "Rotate")],
                        max_length=16,
                    ),
                ),
                ("request_verifier", models.CharField(max_length=64)),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issuance_receipt",
                        to="identity.installationactor",
                    ),
                ),
            ],
        ),
    ]
