# Generated by Django 5.2.17 on 2026-08-12 16:49

import django.db.models.deletion
from django.db import migrations, models


def backfill_link_request_receipts(apps, schema_editor):
    ActorAccountLink = apps.get_model("identity", "ActorAccountLink")
    ActorAccountLinkReceipt = apps.get_model("identity", "ActorAccountLinkReceipt")
    for link in ActorAccountLink.objects.using(schema_editor.connection.alias).iterator():
        ActorAccountLinkReceipt.objects.using(schema_editor.connection.alias).create(
            request_id=link.request_id,
            link_id=link.pk,
        )


def restore_initial_link_request_ids(apps, schema_editor):
    ActorAccountLink = apps.get_model("identity", "ActorAccountLink")
    ActorAccountLinkReceipt = apps.get_model("identity", "ActorAccountLinkReceipt")
    database = schema_editor.connection.alias
    for link in ActorAccountLink.objects.using(database).iterator():
        receipt = (
            ActorAccountLinkReceipt.objects.using(database)
            .filter(link_id=link.pk)
            .order_by("completed_at", "request_id")
            .first()
        )
        if receipt is not None:
            ActorAccountLink.objects.using(database).filter(pk=link.pk).update(
                request_id=receipt.request_id
            )


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0003_accountdeletionreceipt_identityratebucket_and_more"),
    ]

    operations = [
        # Staging the superseded field as nullable/non-unique lets the reverse
        # migration add empty values, restore one receipt UUID per link, and
        # only then reinstate identity.0003's non-null unique constraint.
        migrations.AlterField(
            model_name="actoraccountlink",
            name="request_id",
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.CreateModel(
            name="ActorAccountLinkReceipt",
            fields=[
                (
                    "request_id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="request_receipts",
                        to="identity.actoraccountlink",
                    ),
                ),
            ],
        ),
        migrations.RunPython(
            backfill_link_request_receipts,
            reverse_code=restore_initial_link_request_ids,
        ),
        migrations.RemoveField(
            model_name="actoraccountlink",
            name="request_id",
        ),
    ]
