# Generated by Django 5.2.17 on 2026-08-12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0004_actoraccountlinkrequestreceipt"),
    ]

    operations = [
        # Existing links were created while every durable link was also active
        # attribution, so True is both the backfill and the ongoing default.
        migrations.AddField(
            model_name="actoraccountlink",
            name="is_attribution_active",
            field=models.BooleanField(default=True),
        ),
    ]
